apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/suvmaha/amazon-eks-tutorials
    targetRevision: main
    path: apps/retail-store/manifests/02-clusterip
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-store
  syncPolicy:
    automated:
      prune: true      # delete resources removed from Git
      selfHeal: true   # revert manual kubectl changes
    syncOptions:
      - CreateNamespace=true
